### ISSUE TITLE
Extended event transmission

### ISSUE THREAD

**Issue by officel** [masci/datadog#26]
Hi! Thanks nice action!

There are missing I/F that can be passed to DataDog's API v1.
Can we pass just the source_type_name?

https://docs.datadoghq.com/api/latest/events/#post-an-event
https://docs.datadoghq.com/integrations/faq/list-of-api-source-attribute-value/

**Comment by masci** [comment]
Hi @officel 

actually this should already work, see for example https://github.com/deepset-ai/haystack/blob/9612aa90bbd1d32f133163842e140d598fc07515/.github/workflows/license_compliance.yml#L76-L87 

The interface in https://github.com/masci/datadog/blob/68f124e429317cc02e17965df6d08c75056cb45d/src/datadog.ts#L12 should be fixed indeed but in the meantime you can try use the action as it is.

**Comment by officel** [comment]
Hi @masci 

Thanks for letting me know!
I thought it was not directly mentioned in the code so I thought it was not available.
I tried it and it seems to work properly!

```
    - name: Send event to Datadog
      uses: masci/datadog@v1
      with:
        api-key: ${{ inputs.secrets_datadog_api_key }}
        events: |
          - title: "${{ inputs.title }}"
            text: "${{ inputs.text }}"
            alert_type: "${{ inputs.alert_type }}"
            source_type_name: "Github"
            host: "${{ inputs.host }}"
            priority: "normal"
            tags:
              - "repos:${{ github.repository }}"
              - "working-directory:${{ inputs.working-directory }}"
```
